### ISSUE TITLE
It would be nice to use Jupyter Notebook

### ISSUE THREAD

**Issue by ad3429** [SJRodgers1005/intro-data-capstone-musclehub#1]
Are you familiar with Jupyter Notebooks? Currently you just provided your .py file, but if you put your code in a Jupyter notebook, you can very nicely see all of the output and all of the visualizations, which makes it very nice and easy to understand. I would recommend trying to set that up as a next possible step.

**Comment by InsightfulShawn** [comment]
Yes, I had coded for this project in Jupyter Notebook. The instructions told me to save my IPython file as .py file. I still have my Jupyter Notebook with all the output and visualizations. Should I resubmit the project with my Jupyter Notebook file?
Thanks.
