### ISSUE TITLE
slides are a bit cluttered

### ISSUE THREAD

**Issue by ad3429** [SJRodgers1005/intro-data-capstone-musclehub#2]
The content in your slides is generally very good, however I did notice that it can be a bit cluttered and contain too much information on each slide. Perhaps it would be better if the information was spread out over many slides rather than all condensed in a few.

**Comment by InsightfulShawn** [comment]
I reviewed the slides in my presentation. That is a good callout. I should had and will spread out the information. It can become hard to read so much on a single slide. 
Thank you.
