### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by ad3429** [SJRodgers1005/intro-data-capstone-musclehub#3]
**Summary Grade: Satisfactory**

Overall, this was project was very nicely done - great job!

Your Chi-Squared Tests are accurate and your visualizations look very good - they provide a lot of insight into the data. Your charts are visually appealing and your visualizations communicate each of your points quite well. The slides in general are nicely done however at times I felt that there was too much information cluttered in some of the slides so perhaps it may be better to spread it out. 

I would also recommend putting your code in a Jupyter Notebook to make it much easier for someone to visually see the output of your code and also perform modifications if they would like to play around with it.

Your recommendations are very helpful, and the insights you were able to draw are definitely interesting. Hopefully you can continue to play around with this dataset or other datasets that you find interesting to continue the research. Great job! :)

**Comment by InsightfulShawn** [comment]
Thank you for your recommendation and reviewing my project. It was good challenge of what I have learned with Codecademy over the last 3 months. 
I will continue to seek out projects to challenge me as I grow in the field of data analytics.
Thank you.

**Comment by InsightfulShawn** [comment]
When should I expect my certification?

Thank you again.
